# Do not edit. Generated by the configure script.
{ 'target_defaults': { 'cflags': [],
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'deps_path': 'deps',
                 'host_arch': 'x64',
                 'python': 'C:\\depot_tools\\python276_bin\\python.exe',
                 'target_arch': 'x64'}}
